### ISSUE TITLE
Tasks - Server Side

### ISSUE THREAD

**Issue by fergalddaly** [Keroberos/sam#44]
# TASKS CREATION AND UPDATES ON SERVER SIDE

## CREATE INITIAL SET OF TASKS
In the init service create the following tasks from start month to current month:

For each month
Due Date = last day of month.
Order as below. Status as below.
SUBMIT_TIMESHEET, ISSUE_INVOICE, SUBMIT_EXPENSES, UPLOAD_BANK_ACCOUNT, RECONCILE_BANK_ACCOUNT, SUBMIT_VAT_RETURN

1. SUBMIT_TIMESHEET = TODO
1. ISSUE_INVOICE  --- status=HAS_PREREQUISTE_TASKS
1. SUBMIT_EXPENSES = TODO *** LEAVING THIS OUT FOR NOW
1. UPLOAD_BANK_ACCOUNT --> moved to #64 
1. RECONCILE_BANK_ACCOUNT = TODO 
1. VAT_RETURN = HAS_PREREQUISTE_TASKS

## CHANGE OF STATUS

It is my opinion Events should be used to support this.
This way, we don't introduce task update code in many places.
https://spring.io/blog/2015/02/11/better-application-events-in-spring-framework-4-2

### TIMESHEET change of status
When the timesheet changes status from COMPLETE to SUBMITTED then
1.  Change the timesheet task from TODO to COMPLETED
1.  Change SUBMIT_INVOICE task status from HAS_PREREQUISTE_TASKS to TODO
1.  Also update the invoice with the number of days worked.

A timesheet can change back to status COMPLETE from status SUBMITTED (retract button) - the above changes should be reversed if that happens.

### INVOICE change of status  
When the INVOICE changes status to ISSUED then
1.  Change the INVOICE task from TODO to COMPLETED

### RECONCILE_BANK_ACCOUNT
When the BankStatement changes status to UPLODED to RECONCILED then
1.  Change the RECONCILE_BANK_ACCOUNT task from TODO to COMPLETED
2. If a VAT return task exists for the month then change it from HAS_xx to TODO

### SUBMIT_VAT_RETURN  

When a ROS payment is made (offline) and the details recorded in the vat return, then set the task to completed.

**Comment by fergalddaly** [comment]
d06d4d0d3d027b2910ff099b3e844c484382002b committed - first part of the requirements completed.

**Comment by fergalddaly** [comment]
b753ff211f2736b17344a7c585c7b1b1fa347171 committed - event listener added.

**Comment by fergalddaly** [comment]
9e70785b521e71afe8406ebdf90fb205988e59cd commited - add in monthlytasks support.
Not working.  Issue below.
@Keroberos - can you help with this ?  The association isn't working. Don't know where to fix this.

![image](https://user-images.githubusercontent.com/2511712/28498720-ffeac8ee-6f9b-11e7-9d2f-f16be868b853.png)




```
Caused by: org.hibernate.exception.ConstraintViolationException: could not execute statement
	at org.hibernate.exception.internal.SQLStateConversionDelegate.convert(SQLStateConversionDelegate.java:112)
	at org.hibernate.exception.internal.StandardSQLExceptionConverter.convert(StandardSQLExceptionConverter.java:42)
	at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:111)
	at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:97)
	at org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.executeUpdate(ResultSetReturnImpl.java:208)
	at org.hibernate.engine.jdbc.batch.internal.NonBatchingBatch.addToBatch(NonBatchingBatch.java:45)
	at org.hibernate.persister.collection.AbstractCollectionPersister.recreate(AbstractCollectionPersister.java:1323)
	at org.hibernate.action.internal.CollectionRecreateAction.execute(CollectionRecreateAction.java:50)
	at org.hibernate.engine.spi.ActionQueue.executeActions(ActionQueue.java:586)
	at org.hibernate.engine.spi.ActionQueue.executeActions(ActionQueue.java:460)
	at org.hibernate.event.internal.AbstractFlushingEventListener.performExecutions(AbstractFlushingEventListener.java:337)
	at org.hibernate.event.internal.DefaultFlushEventListener.onFlush(DefaultFlushEventListener.java:39)
	at org.hibernate.internal.SessionImpl.doFlush(SessionImpl.java:1428)
	at org.hibernate.internal.SessionImpl.managedFlush(SessionImpl.java:484)
	at org.hibernate.internal.SessionImpl.flushBeforeTransactionCompletion(SessionImpl.java:3190)
	at org.hibernate.internal.SessionImpl.beforeTransactionCompletion(SessionImpl.java:2404)
	at org.hibernate.engine.jdbc.internal.JdbcCoordinatorImpl.beforeTransactionCompletion(JdbcCoordinatorImpl.java:467)
	at org.hibernate.resource.transaction.backend.jdbc.internal.JdbcResourceLocalTransactionCoordinatorImpl.beforeCompletionCallback(JdbcResourceLocalTransactionCoordinatorImpl.java:146)
	at org.hibernate.resource.transaction.backend.jdbc.internal.JdbcResourceLocalTransactionCoordinatorImpl.access$100(JdbcResourceLocalTransactionCoordinatorImpl.java:38)
	at org.hibernate.resource.transaction.backend.jdbc.internal.JdbcResourceLocalTransactionCoordinatorImpl$TransactionDriverControlImpl.commit(JdbcResourceLocalTransactionCoordinatorImpl.java:220)
	at org.hibernate.engine.transaction.internal.TransactionImpl.commit(TransactionImpl.java:68)
	at org.springframework.orm.jpa.JpaTransactionManager.doCommit(JpaTransactionManager.java:517)
	... 156 common frames omitted
Caused by: org.h2.jdbc.JdbcSQLException: NULL not allowed for column "TASKS_ID"; SQL statement:
insert into monthly_tasks_tasks (monthly_tasks_id, tasks_id) values (?, ?) [23502-195]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.table.Column.validateConvertUpdateSequence(Column.java:345)
	at org.h2.table.Table.validateConvertUpdateSequence(Table.java:793)
	at org.h2.command.dml.Insert.insertRows(Insert.java:151)
	at org.h2.command.dml.Insert.update(Insert.java:114)
	at org.h2.command.CommandContainer.update(CommandContainer.java:101)
	at org.h2.command.Command.executeUpdate(Command.java:260)
	at org.h2.jdbc.JdbcPreparedStatement.executeUpdateInternal(JdbcPreparedStatement.java:164)
	at org.h2.jdbc.JdbcPreparedStatement.executeUpdate(JdbcPreparedStatement.java:150)
	at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeUpdate(ProxyPreparedStatement.java:61)
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeUpdate(HikariProxyPreparedStatement.java)
	at org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.executeUpdate(ResultSetReturnImpl.java:205)
	... 173 common frames omitted
```

**Comment by Keroberos** [comment]
let me look into that

**Comment by fergalddaly** [comment]
d0e4c77c6abe5151730a4a85585371e15d569daa commited.
Task complete.
Branch merged to master.

**Comment by fergalddaly** [comment]
@Keroberos  - when you're happy with these changes, can you close the task.

**Comment by Keroberos** [comment]
Everything looks fine
